# Generated by Django 3.1.6 on 2021-02-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('end', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
