# Generated by Django 3.1.6 on 2021-02-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
